config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dinosaurs/map", to: "dinosaurs#map"
  resources :dinosaurs, only: %i[index show] do
    resources :bookings, only: :create
  end
  resources :my_bookings, only: :index
  resources :my_dinosaurs, only: %i[index new create destroy]
  resources :my_rents, only: :index do
    member do
      patch :accept
      patch :deny
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dinosaur

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  def duration
    (self.end_date - self.start_date) / 60 / 60 / 24
  end

  private

  def end_date_after_start_date
    errors.add(:end_date, "can't be before start date") if end_date < start_date
  end
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_many :bookings, dependent: :nullify
  has_many_attached :photos

  validates :address, :name, :species, :price_per_day, :photos, presence: true
  validates :description, length: { minimum: 6 }

  SPECIES = %i[Tyrannosaur Diplodocus Stegosaur Allosaur Velociraptor Galliminus Triceratops Archeopteryx Spinosaur Pterodactyl]

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dinosaurs, dependent: :destroy
  has_many :bookings, dependent: :nullify
  has_many :owner_bookings, through: :dinosaurs, source: :bookings
  has_one_attached :avatar

  validates :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dinosaurs_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @booking.dinosaur = Dinosaur.find(params[:dinosaur_id])
    @booking.user = current_user
    @booking.booking_price = @booking.duration * @booking.dinosaur.price_per_day
    if @booking.save!
      redirect_to my_bookings_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show map]

  def index
    if params[:query].present?
      @dinos = Dinosaur.where(species: params[:query])
    else
      @dinos = Dinosaur.all
    end
  end

  def show
    @dino = Dinosaur.find(params[:id])
    @booking = Booking.new
  end

  def create
  end

  def map
    @dinos = Dinosaur.all
    # The `geocoded` scope filters only dinos with coordinates
    @markers = @dinos.geocoded.map do |dino|
      {
        lat: dino.latitude,
        lng: dino.longitude,
        info_window: render_to_string(partial: "info_window", locals: {dino: dino}),
        image_url: helpers.asset_url("patte.png")
      }
    end
  end
end

app/controllers/my_bookings_controller.rb
class MyBookingsController < ApplicationController
  def index
    @renter = current_user
    @bookings = current_user.bookings
  end
end

app/controllers/my_dinosaurs_controller.rb
class MyDinosaursController < ApplicationController
  def new
    @dino = Dinosaur.new
  end

  def create
    @dino = Dinosaur.new(dino_params)
    @dino.price_per_day = @dino.price_per_day * 100
    @dino.owner = current_user

    if @dino.save
      redirect_to my_dinosaurs_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @owner_dinos = current_user.dinosaurs
  end

  def destroy
    @dino = Dinosaur.find(params[:id])
    @dino.destroy

    redirect_to my_dinosaurs_path, status: :see_other
  end

  private

  def dino_params
    params.require(:dinosaur).permit(:name, :species, :address, :description, :price_per_day, photos: [])
  end
end

app/controllers/my_rents_controller.rb
class MyRentsController < ApplicationController
  def index
    @bookings = current_user.owner_bookings.order(created_at: :desc)
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accept"
    @booking.save

    redirect_to my_rents_path(current_user)
  end

  def deny
    @booking = Booking.find(params[:id])
    @booking.status = "deny"
    @booking.save

    redirect_to my_rents_path(current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @hide_notice = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dinosaurs/_info_window.html.erb
<%= link_to dinosaur_path(dino), class: "text-decoration-none" do %>
  <%= cl_image_tag dino.photos[0].key, crop: :fill %>
  <h5 class="text-center mt-3"><%= dino.name %></h5>
  <div class="row align-items-center mx-1 mb-0">
    <div class="col-7 ps-2 pe-0">
      <p><%= raw("<i class='fa-solid fa-paw'></i>")%> <%=dino.species %></p>
      <p><%= raw("<i class='fa-solid fa-location-crosshairs'></i>")%> <%=dino.address %></p>
    </div>
    <div class="col-5 ps-0 pe-2">
      <p><%= raw("<i class='fa-solid fa-euro-sign'></i>")%> <strong><%=dino.price_per_day.fdiv(100) %></strong> / day</p>
    </div>
  </div>
<% end %>

app/views/dinosaurs/index.html.erb
<div class="container my-5">
  <div class="mb-5 search-forms">
    <%= form_with url: dinosaurs_path, method: :get, class: "w-100" do |f| %>
      <div class="form-species-select">
        <%= select_tag :query,
          options_for_select(Dinosaur::SPECIES, params[:query]),
          include_blank: true,
          class: "form-control search-form-control form-shadow",
          prompt: "Search a species"
        %>

        <div class="form-species-submit form-shadow">
          <%= f.submit "Find a species", class: "btn btn-outline-secondary text-white" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <% @dinos.each do |dino| %>
      <div class="col-12 col-sm-6 col-lg-4 d-flex justify-content-center p-0">
        <%= link_to dinosaur_path(dino), class: "text-decoration-none" do %>
          <div class="card-dino mb-5 text-white">
            <%= cl_image_tag dino.photos[0].key, crop: :fill, width: 300 %>
            <div class="card-dino-infos">
              <div></div>
              <%= cl_image_tag dino.owner.avatar.key, class: "card-dino-user avatar-bordered", crop: :thumb, width: 100 %>
            </div>
            <div>
              <h5 class="text-center"><%= dino.name %></h5>
              <div class="row align-items-center mx-1 mb-3">
                <div class="col-7 ps-2 pe-0">
                  <p><%= raw("<i class='fa-solid fa-paw'></i>")%> <%=dino.species %></p>
                  <p><%= raw("<i class='fa-solid fa-location-crosshairs'></i>")%> <%=dino.address %></p>
                </div>
                <div class="col-5 ps-0 pe-2">
                  <p><%= raw("<i class='fa-solid fa-euro-sign'></i>")%> <strong><%=dino.price_per_day.fdiv(100) %></strong> / day</p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="sticky-btn">
    <%= link_to "Display map", dinosaurs_map_path %>
  </div>

</div>

app/views/dinosaurs/map.html.erb
<div class="container my-5">
  <div id="map"style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

  <div class="sticky-btn">
    <%= link_to "Display list", dinosaurs_path %>
  </div>
</div>

app/views/dinosaurs/show.html.erb
<div class="container page mt-5">
  <div class="row">
    <div class="col-12 col-lg-8">

      <% @dino.photos.each do |p| %>
        <%= cl_image_tag p.key, height: 300, width: 700, crop: :fill  %>
      <% end %>
      <h2 id="desc-name"><%=@dino.name%></h2>
      <p id="desc-species"><%= raw("<i class='fa-solid fa-paw'></i>") %><em><%= @dino.species %></em></p>
      <p class="mt-24"><%=@dino.description%></p>
      <p><%= raw("<i class='fa-solid fa-euro-sign'></i>") %> <strong><%= @dino.price_per_day.fdiv(100) %></strong> / day</p>
      <p><%= raw("<i class='fa-solid fa-location-crosshairs'></i>")%> <%=@dino.address %></p>
    </div>
    <div class="col-12 col-lg-4">
      <% if current_user == @dino.owner %>
        <h3 id="my-reminder-title"> Who want my dino </h3>
        <% if @dino.bookings.count != 0 %>
          <div class="container card-reminder">
            <% @dino.bookings.reverse.each do |b| %>
              <%= link_to my_rents_path, class: "text-decoration-none" do %>
                <div class="row justify-content-between">
                  <div class="col-6 text-center">
                    <p><%= b.user.first_name %></p>
                    <p><%= b.user.last_name %></p>
                  </div>
                  <div class="col-6">
                    <h5 class="<%= b.status %>">
                      <% if b.status == "accept" %>
                        <%= "Accepted" %>
                      <% elsif b.status == "deny" %>
                        <%= "Denied" %>
                      <% else %>
                        <%= "Pending..." %>
                      <% end %>
                      </h5>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <p class="text-center my-5"><em>Feeling lonely... Waiting for a booker</em></p>
        <% end %>
      <% else %>
        <div data-controller="display-price" data-display-price-dino-price-value="<%=@dino.price_per_day.fdiv(100)%>" class="rounded border p-2 border-bottom">
        <h2 class="text-center"><%="Book your Dino"%></h2>
        <hr />
          <%= simple_form_for [@dino, @booking], data: { controller: 'flatpickr' } do |f| %>
            <%= f.input :start_date, as: :date, html5: true, label: "Start of booking", input_html: {min: Date.today, data: {action: "change->display-price#compute", display_price_target: "startDate", flatpickr_target: "startTime" }}%>
            <%= f.input :end_date, as: :date, html5: true, label: "End of booking", input_html: {min: Date.today, data: {action: "change->display-price#compute", display_price_target: "endDate", flatpickr_target: "endTime" }}%>
            <p class="text-center"><b><span data-display-price-target="totalPrice"></span></b></p>
            <div class="d-flex justify-content-center">
              <%= f.button :submit, "Book now", disabled: true, class: "btn btn-outline-secondary", data: { display_price_target: "button" }%>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid mx-3">
    <%= link_to dinosaurs_path do %>
      <div class="main-title">
        <svg viewBox="0 0 600 300">
          <!-- Symbol-->
          <symbol id="s-text">
            <text text-anchor="middle" x="31%" y="50%" dy=".35em">Rent a Dino</text>
          </symbol>
          <!-- Duplicate symbols-->
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
        </svg>
      </div>
    <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active d-flex align-items-center m-3">
          <%= link_to "Add a dino", new_my_dinosaur_path, class: "btn btn-outline-secondary nav-link" %>
        </li>
        <% if current_user %>
          <li class="nav-item dropdown d-flex align-items-center">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cl_image_path current_user.avatar.key, crop: :thumb, width: 100 %>" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "My dinos", my_dinosaurs_path, class: "dropdown-item" %>
              <%= link_to "My rents", my_rents_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
                  class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <div class="d-flex align-items-center">
            <%= link_to "log in", new_user_session_path, class: "btn btn-ghost" %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navbar_login.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light">
  <div class="container-fluid mx-3">
    <%= link_to dinosaurs_path do %>
      <div class="main-title">
        <svg viewBox="0 0 600 300">
          <!-- Symbol-->
          <symbol id="s-text">
            <text text-anchor="middle" x="50%" y="50%" dy=".35em">Rent a Dino</text>
          </symbol>
          <!-- Duplicate symbols-->
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
          <use class="text" xlink:href="#s-text"></use>
        </svg>
      </div>
    <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="d-flex align-items-center">
        <%= link_to "Home", root_path, class: "btn btn-ghost" %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentADino</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body class="background_img text_white">
    <%= render 'layouts/navbar' unless current_page?(root_path) || current_page?(new_user_session_path) %>
    <%= render 'layouts/navbar_login' if current_page?(new_user_session_path) %>
    <div class="main-container">
      <p class="notice m-0 <%= "d-none" if @hide_notice %>"><%= notice %></p>
      <p class="alert m-0"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/my_bookings/index.html.erb
<div class="container text-center page">
  <h2 id='my-booking-title'>My booked dinos</h2>
  <% @bookings.reverse.each do |b| %>
  <div class="container card-booked-dino">
    <div class="row justify-content-between">
      <div class="col-2 card-image">
        <%= cl_image_tag b.dinosaur.photos[0].key, height: 100, width: 100, crop: :fill, id: "dino-avatar" %>
      </div>
      <div class="col-2">
        <p><%= link_to b.dinosaur.name, dinosaur_path(b.dinosaur), class: "name" %></p>
        <p class="species"><em><%= raw("<i class='fa-solid fa-paw'></i>")%><%= b.dinosaur.species %></em></p>
      </div>
      <div class="col-2 text-center">
        <p><b><%= b.start_date.day %>/<%= b.start_date.month %>/<%= b.start_date.year %></b></p>
        <p><b>⇓</b></p>
        <p><b><%= b.end_date.day %>/<%= b.end_date.month %>/<%= b.end_date.year %></b></p>
      </div>
      <div class="col-2 text-center">
        <p id="booking-price">Total : <%= b.booking_price.fdiv(100) %>€</p>
      </div>
      <div class="col-2">
        <p id="client">Owned by:<br><%= b.dinosaur.owner.first_name%> <%= b.dinosaur.owner.last_name%></p>
      </div>
      <div class="col-2">
        <h5 class="<%= b.status %>">
          <% if b.status == "accept" %>
            <%= "Accepted" %>
          <% elsif b.status == "deny" %>
            <%= "Denied" %>
          <% else %>
            <%= "Pending..." %>
          <% end %>
        </h5>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/my_dinosaurs/index.html.erb
<div class="container my-5">
  <div class="row">
    <% @owner_dinos.each do |dino| %>
      <div class="col-12 col-sm-6 col-lg-4 d-flex justify-content-center p-0 position-relative">
        <%= link_to raw("<i class='fa-solid fa-trash-can'></i>"), my_dinosaur_path(dino), class: "text-decoration-none destroy-icon", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <%= link_to dinosaur_path(dino), class: "text-decoration-none" do %>
          <div class="card-dino mb-5 text-white position-relative">
            <%= cl_image_tag dino.photos[0].key, crop: :fill, width: 300 %>
            <div class="card-dino-infos">
              <div></div>
              <%= cl_image_tag dino.owner.avatar.key, class: "card-dino-user avatar-bordered", crop: :thumb, width: 100 %>
            </div>
            <div>
              <h5 class="text-center"><%= dino.name %></h5>
              <div class="row align-items-center mx-1 mb-3">
                <div class="col-7 ps-2 pe-0">
                  <p><%= raw("<i class='fa-solid fa-paw'></i>")%> <%=dino.species %></p>
                  <p><%= raw("<i class='fa-solid fa-location-crosshairs'></i>")%> <%=dino.address %></p>
                </div>
                <div class="col-5 ps-0 pe-2">
                  <p><%= raw("<i class='fa-solid fa-euro-sign'></i>")%> <strong><%=dino.price_per_day.fdiv(100) %></strong> / day</p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="col-12 col-sm-6 col-lg-4 d-flex justify-content-center p-0">
      <%= link_to new_my_dinosaur_path, class: "text-decoration-none w-auto" do %>
        <div class="card-dino mb-5 bg-black text-white opacity-85 border border-white">
          <div class="add-dino d-flex justify-content-center align-items-center">
            <div class="fa-solid fa-plus"></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/my_dinosaurs/new.html.erb
<div class="container my-6 text-white opacity-85 col-12 col-md-6 col-lg-4 p-3 form-shadow" >
  <h1 class= "text-center">Add a Dino</h1>
  <hr />
  <h4 class="fa-light fa-file-circle-info">Enter the Dino's info here :</h4>
  <%= simple_form_for(@dino, method: :post, url: my_dinosaurs_path) do |f| %>
    <div class="form-inputs mt-3 mb-3">
      <div class="d-flex justify-content-between">
        <div class="me-2 text-white">
          <%= f.input :name %>
        </div>
        <div class= "ms-2">
          <%= f.input :species, collection: Dinosaur::SPECIES %>
        </div>
      </div>
      <%= f.input :address %>
      <%= f.input :description,  placeholder: "Mininum 6 characters"%>
      <%= f.input :price_per_day, label: "Price €" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Pictures" %>
    </div>
    <div class="form-inputs text-center mt-4">
      <%= f.button :submit, "Rent my dino", class: "form-button", style: "width: 50%" %>
    </div>
  <% end %>
</div>

app/views/my_rents/index.html.erb
<%# On affiche les user_bookings %>

<div class="container text-center page">
  <h2 id='my-booking-title'>My rents</h2>
  <% @bookings.each do |b| %>
  <div class="container card-booked-dino">
    <div class="row justify-content-between">
      <div class="col-2 card-image">
        <%= cl_image_tag b.dinosaur.photos[0].key, height: 100, width: 100, crop: :fill, id: "dino-avatar" %>
      </div>
      <div class="col-2">
        <p><%= link_to b.dinosaur.name, dinosaur_path(b.dinosaur), class: "name" %></p>
        <p class="species"><em><%= raw("<i class='fa-solid fa-paw'></i>")%><%= b.dinosaur.species %></em></p>
      </div>
      <div class="col-2 text-center">
        <p><b><%= b.start_date.day %>/<%= b.start_date.month %>/<%= b.start_date.year %></b></p>
        <p><b>⇓</b></p>
        <p><b><%= b.end_date.day %>/<%= b.end_date.month %>/<%= b.end_date.year %></b></p>
      </div>
      <div class="col-2 text-center">
        <p id="booking-price">Total : <%= b.booking_price.fdiv(100) %>€</p>
      </div>
      <div class="col-2">
        <p id="client">Booked by:<br><%= b.user.first_name%> <%= b.user.last_name%></p>
      </div>
      <div class="col-2">
        <h5 class="<%= b.status %> m-0">
          <% if b.status == "accept" %>
            <%= "Accepted" %>
          <% elsif b.status == "deny" %>
            <%= "Denied" %>
          <% else %>
            <%= "Pending..." %>
          <% end %>
        </h5>
        <% if b.status == "pending" %>
        <div class="d-flex justify-content-around mt-3">
            <%= link_to "✓", accept_my_rent_path(b), data: {turbo_method: :patch}, class: "badge rounded-pill", id: 'check-green'%>
            <%= link_to "✕", deny_my_rent_path(b), data: {turbo_method: :patch}, class: 'badge rounded-pill bg-danger', id: 'check-red'%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container-fluid d-flex justify-content-between align-items-center">
    <div class="main-title">
      <svg viewBox="0 0 600 300">
        <!-- Symbol-->
        <symbol id="s-text">
          <text text-anchor="middle" x="50%" y="50%" dy=".35em">Rent a Dino</text>
        </symbol>
        <!-- Duplicate symbols-->
        <use class="text" xlink:href="#s-text"></use>
        <use class="text" xlink:href="#s-text"></use>
        <use class="text" xlink:href="#s-text"></use>
        <use class="text" xlink:href="#s-text"></use>
        <use class="text" xlink:href="#s-text"></use>
      </svg>
    </div>
    <% if current_user %>
      <ul style="list-style: none">
        <li class="nav-item dropdown">
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cl_image_path current_user.avatar.key, crop: :thumb, width: 100 %>" />
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My dinos", my_dinosaurs_path, class: "dropdown-item" %>
            <%= link_to "My rents", my_rents_path, class: "dropdown-item" %>
            <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
                class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    <% else %>
      <div class="btn-login">
        <%= link_to "log in", new_user_session_path, class: "btn btn-ghost" %>
      </div>
    <% end %>
  </div>
  <div class="btn-get-started" data-controller="roar-button" data-roar-button-sound-value="<%= asset_path('roar.mp3')%>">
    <%= link_to "Find your dino", dinosaurs_path, class: "btn btn-flat", data: { action: "click->roar-button#play" } %>
  </div>
  <div class="timeline-position fixed-bottom">
    <div id="timeline-wrap">
      <div id="timeline"></div>
      <div class="marker mfirst timeline-icon one">
        <div class="marker-text">
          <p>Find it</p>
        </div>
        <i class="fa fa-person"></i>
      </div>
      <div class="marker m2 timeline-icon two">
      <div class="marker-text">
          <p>Rent it</p>
        </div>
        <i class="fa fa-credit-card"></i>
      </div>
      <div class="marker m3 timeline-icon three">
        <div class="marker-text">
          <p>Meet it</p>
        </div>
        <i class="fa fa-dragon"></i>
      </div>
      <div class="marker mlast timeline-icon four">
        <div class="marker-text">
          <p>Love it</p>
        </div>
        <i class="fa fa-heart"></i>
      </div>
    </div>
  </div>
</div>